version: '2'
services:
  cabin_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: aessocializacion
      MYSQL_USER: aessocializacion
      MYSQL_PASSWORD: aessocializacion

